### ISSUE TITLE
Exposed Firebase API Token in public repo

### ISSUE THREAD

**Issue by wy** [DevNight-CNX/covid-19-cnx#20]
https://github.com/DevNight-CNX/covid-19-cnx/blob/74becb67036944909814e8f1d0f78a727c43f809/src/App.js#L19

Please avoid using your API taken in public repo code as it may get compromised.

Thanks

**Comment by Elecweb** [comment]
@wy user still can get it by inspecting our code. but it's should not in public repo anyways, Thank for you concern
